openapi: 3.0.1
info:
  contact:
    email: g2_family_lock@gmail.com
    name: G2 - Family Lock
    url: https://s-computing.blogspot.com/2020/09/familylock.html
  description: This API provides the neccesary data for the Family Lock project
  title: Family Lock API
  version: "1.0"
servers:
- url: https://raw.githubusercontent.com/
paths:
  /device_MAC:
    delete:
      description: Delete the selected Device MAC.
      operationId: delete_device_mac
      parameters:
      - description: Device MAC
        explode: true
        in: query
        name: DeviceMAC
        required: true
        schema:
          type: string
        style: form 
        example:
          person_MAC: ff:ff:ff:ff:ff
        x-body-name: device_mac
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Deleted
                title: Deleted
                type: string
          description: Deleted
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Delete the device MAC.
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
      x-openapi-router-controller: openapi_server.controllers.device_mac_controller
    get:
      description: Return all the MAC devices
      operationId: get_device_mac
      parameters:
      - description: Device MAC
        explode: true
        in: query
        name: DeviceMAC
        required: false
        schema:
          type: string
        style: form
        example:
          person_MAC: ff:ff:ff:ff:ff
        x-body-name: device_mac
      responses:
        200:
          content:
            text/plain:
              schema:
                example: OK
                title: OK
                type: string
            application/json:
              schema:
                example: OK
                title: OK
                type: string
          description: OK
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Return all the devices MACs
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
      x-openapi-router-controller: openapi_server.controllers.device_mac_controller
    post:
      description: Addition of a new device MAC
      operationId: post_device_mac
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceMAC'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
        409:
          content:
            text/plain:
              schema:
                example: There is a conflict
                title: Index conflict
                type: string
          description: DB index conflict
      summary: Add a new Device MAC.
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
      x-openapi-router-controller: openapi_server.controllers.device_mac_controller
    put:
      description: Update a device MAC
      operationId: put_device_mac
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewDeviceMAC'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
        409:
          content:
            text/plain:
              schema:
                example: There is a conflict
                title: Index conflict
                type: string
          description: DB index conflict
      summary: Update a device MAC
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
      x-openapi-router-controller: openapi_server.controllers.device_mac_controller
components:
  schemas:
    DeviceMAC:
      example:
        person_MAC: [ff:ff:ff:ff:ff]
        person_name: Luis
        person_phone_number: "000000000"
        notification: true
        dest_MAC: ""
      properties:
        person_MAC:
          type: array
          items:
            type: string
        person_name:
          type: string
        person_phone_number:
          type: string
        notification:
          type: boolean
        dest_MAC:
          type: string
      type: object
      x-body-name: device_mac
          
    NewDeviceMAC:
      example:
        new_MAC: 00:00:00:00:00
        old_MAC: ff:ff:ff:ff:ff
      properties:
        old_MAC:
          type: string
        new_MAC:
          type: string
      type: object
      x-body-name: new_device_mac

